spring:
  application:
    name: JWT-Auth-Service
  profiles:
    active: development

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jwt;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: true

  jwt:
    secret: VGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25XaXRoSGlnaFNlY3VyaXR5
    expirationTime: 900000 # 15분
    refreshTokenExpirationTime: 604800000 # 7일

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# 로깅 설정
logging:
  level:
    com.jwtauth: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/jwt-auth.log

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# 애플리케이션 정보
info:
  app:
    name: JWT Authentication Service
    description: Spring Boot JWT Authentication and Authorization Service
    version: 1.0.0
    developer: JWT Auth Team

---
# 프로덕션 프로필
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/jwt_auth_prod}
    username: ${DB_USERNAME:jwt_user}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  jwt:
    secret: ${JWT_SECRET:}
    expirationTime: ${JWT_EXPIRATION:900000}
    refreshTokenExpirationTime: ${JWT_REFRESH_EXPIRATION:604800000}
  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN
    com.jwtauth: INFO
    org.springframework.security: WARN
